### Get all cats
GET http://127.0.0.1:3000/api/v1/cats

### Get cat by id
GET http://127.0.0.1:3000/api/v1/cats/41

### Get cats by user id
GET http://127.0.0.1:3000/api/v1/cats/owner/37

### Create new cat (with image)
POST http://127.0.0.1:3000/api/v1/cats
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="cat_name"

Barsik
--WebAppBoundary
Content-Disposition: form-data; name="weight"

6
--WebAppBoundary
Content-Disposition: form-data; name="owner"

37
--WebAppBoundary
Content-Disposition: form-data; name="birthdate"

2025-02-23
--WebAppBoundary
Content-Disposition: form-data; name="cat"; filename="dog.jpg"
Content-Type: image/jpeg

< ./dog.jpg
--WebAppBoundary--

### Update cat
PUT http://127.0.0.1:3000/api/v1/cats/45
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "cat_name": "Barsik Updated",
  "weight": 7,
  "owner": 37,
  "filename": "1775488962844-dog.jpg",
  "birthdate": "2025-02-23"
}

### Delete cat
DELETE http://127.0.0.1:3000/api/v1/cats/45
Authorization: Bearer {{token}}
