### Get all users
GET http://127.0.0.1:3000/api/v1/users

### Get user by id
GET http://127.0.0.1:3000/api/v1/users/37

### Create new user
POST http://127.0.0.1:3000/api/v1/users
Content-Type: application/json

{
  "name": "Jane Doe",
  "username": "janedoe",
  "email": "jane@metropolia.fi",
  "role": "user",
  "password": "secret123"
}

### Update user
PUT http://127.0.0.1:3000/api/v1/users/37
Content-Type: application/json

{
  "name": "John Updated",
  "username": "johnupdated",
  "email": "john.updated@metropolia.fi",
  "role": "admin",
  "password": "newpassword123"
}

### Delete user
DELETE http://127.0.0.1:3000/api/v1/users/37
